

export const menuItems = [
  {
    id: 1,
    name: "Chicken Fajita Pizza",
    category: "Chicken",
    prices: {
      Small: "280 AFN",
      Medium: "420 AFN",
      Large: "580 AFN",
      Family: "780 AFN",
    },
    description: "Spicy chicken fajita with bell peppers, onions, jalapenos, and melted cheese.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 2,
    name: "Vegetable Pizza",
    category: "Vegetable",
    prices: {
      Small: "230 AFN",
      Medium: "340 AFN",
      Large: "450 AFN",
      Family: "650 AFN",
    },
    description: "Fresh vegetables, olives, mushrooms, mozzarella, and classic pizza sauce.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 3,
    name: "Cheese Pizza",
    category: "Cheese",
    prices: {
      Small: "220 AFN",
      Medium: "320 AFN",
      Large: "420 AFN",
      Family: "600 AFN",
    },
    description: "A simple favorite with extra mozzarella, cheddar, and rich tomato sauce.",
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 4,
    name: "Special Pizza",
    category: "Special",
    prices: {
      Small: "320 AFN",
      Medium: "480 AFN",
      Large: "650 AFN",
      Family: "880 AFN",
    },
    description: "Loaded house special with chicken, beef, vegetables, cheese, and signature sauce.",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 5,
    name: "Classic Burger",
    category: "Burgers",
    prices: {
      Small: "220 AFN",
      Medium: "250 AFN",
      Large: "280 AFN",
      Family: "360 AFN",
    },
    description: "Beef patty, cheddar, lettuce, tomato, pickles, and burger sauce.",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 6,
    name: "Chicken Burger",
    category: "Burgers",
    prices: {
      Small: "240 AFN",
      Medium: "280 AFN",
      Large: "320 AFN",
      Family: "420 AFN",
    },
    description: "Crispy chicken, lettuce, tomato, cheese, and garlic mayo in a toasted bun.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 7,
    name: "Chicken Shawrma",
    category: "Shawrma",
    prices: {
      Small: "160 AFN",
      Medium: "190 AFN",
      Large: "220 AFN",
      Family: "300 AFN",
    },
    description: "Seasoned chicken, garlic sauce, pickles, fries, and warm flatbread.",
    image: "https://images.unsplash.com/photo-1633321702518-7feccafb94d5?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 8,
    name: "Special Shawrma",
    category: "Shawrma",
    prices: {
      Small: "210 AFN",
      Medium: "250 AFN",
      Large: "300 AFN",
      Family: "420 AFN",
    },
    description: "Extra chicken, cheese, fries, garlic sauce, and house special wrap seasoning.",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 9,
    name: "BBQ Chicken Pizza",
    category: "Chicken",
    prices: {
      Small: "290 AFN",
      Medium: "430 AFN",
      Large: "600 AFN",
      Family: "820 AFN",
    },
    description: "Grilled chicken, barbecue sauce, red onion, mozzarella, and sweet corn.",
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 10,
    name: "Chicken Supreme Pizza",
    category: "Chicken",
    prices: {
      Small: "300 AFN",
      Medium: "450 AFN",
      Large: "620 AFN",
      Family: "850 AFN",
    },
    description: "Chicken, mushrooms, peppers, olives, mozzarella, and house special sauce.",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 11,
    name: "Grilled Chicken Pizza",
    category: "Chicken",
    prices: {
      Small: "270 AFN",
      Medium: "400 AFN",
      Large: "560 AFN",
      Family: "760 AFN",
    },
    description: "Grilled chicken, fresh herbs, mozzarella, onions, and tomato sauce.",
    image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 12,
    name: "Garden Pizza",
    category: "Vegetable",
    prices: {
      Small: "220 AFN",
      Medium: "330 AFN",
      Large: "440 AFN",
      Family: "620 AFN",
    },
    description: "Bell peppers, onions, tomatoes, olives, mushrooms, and mozzarella.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 13,
    name: "Mushroom Pizza",
    category: "Vegetable",
    prices: {
      Small: "230 AFN",
      Medium: "350 AFN",
      Large: "470 AFN",
      Family: "660 AFN",
    },
    description: "Mushrooms, olives, onions, mozzarella, oregano, and tomato sauce.",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 14,
    name: "Corn Vegetable Pizza",
    category: "Vegetable",
    prices: {
      Small: "210 AFN",
      Medium: "320 AFN",
      Large: "430 AFN",
      Family: "600 AFN",
    },
    description: "Sweet corn, peppers, onions, tomatoes, mozzarella, and mild sauce.",
    image: "https://images.unsplash.com/photo-1620374645498-af6bd681a9bd?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 15,
    name: "Double Cheese Pizza",
    category: "Cheese",
    prices: {
      Small: "240 AFN",
      Medium: "350 AFN",
      Large: "470 AFN",
      Family: "650 AFN",
    },
    description: "Extra mozzarella, cheddar, parmesan, and a golden cheesy crust.",
    image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 16,
    name: "Margarita Pizza",
    category: "Cheese",
    prices: {
      Small: "230 AFN",
      Medium: "340 AFN",
      Large: "460 AFN",
      Family: "640 AFN",
    },
    description: "Classic mozzarella, tomato sauce, basil leaves, and olive oil.",
    image: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 17,
    name: "Cream Cheese Pizza",
    category: "Cheese",
    prices: {
      Small: "250 AFN",
      Medium: "370 AFN",
      Large: "500 AFN",
      Family: "690 AFN",
    },
    description: "Mozzarella, cream cheese, cheddar, oregano, and a soft golden crust.",
    image: "https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 18,
    name: "Pizza Town Special",
    category: "Special",
    prices: {
      Small: "350 AFN",
      Medium: "520 AFN",
      Large: "700 AFN",
      Family: "950 AFN",
    },
    description: "Premium chicken, beef, vegetables, cheese, olives, and special sauce.",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 19,
    name: "Beef Special Pizza",
    category: "Special",
    prices: {
      Small: "330 AFN",
      Medium: "500 AFN",
      Large: "680 AFN",
      Family: "920 AFN",
    },
    description: "Seasoned beef, peppers, onions, mushrooms, cheese, and tomato sauce.",
    image: "https://images.unsplash.com/photo-1601924582970-9238bcb495d9?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 20,
    name: "Spicy Special Pizza",
    category: "Special",
    prices: {
      Small: "340 AFN",
      Medium: "510 AFN",
      Large: "690 AFN",
      Family: "930 AFN",
    },
    description: "Hot peppers, chicken, beef, onions, mozzarella, and spicy house sauce.",
    image: "https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 21,
    name: "Double Cheese Burger",
    category: "Burgers",
    prices: {
      Small: "260 AFN",
      Medium: "300 AFN",
      Large: "350 AFN",
      Family: "460 AFN",
    },
    description: "Double beef patty, double cheese, pickles, lettuce, and burger sauce.",
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 22,
    name: "Zinger Burger",
    category: "Burgers",
    prices: {
      Small: "250 AFN",
      Medium: "290 AFN",
      Large: "340 AFN",
      Family: "450 AFN",
    },
    description: "Spicy crispy chicken, lettuce, cheese, tomato, and creamy sauce.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
    isNew: true,
  },
  {
    id: 23,
    name: "Beef Burger",
    category: "Burgers",
    prices: {
      Small: "240 AFN",
      Medium: "280 AFN",
      Large: "330 AFN",
      Family: "440 AFN",
    },
    description: "Grilled beef patty, cheddar, onion, tomato, pickles, and ketchup mayo.",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 24,
    name: "Beef Shawrma",
    category: "Shawrma",
    prices: {
      Small: "180 AFN",
      Medium: "220 AFN",
      Large: "270 AFN",
      Family: "360 AFN",
    },
    description: "Seasoned beef, tahini sauce, pickles, onions, and warm flatbread.",
    image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 25,
    name: "Cheese Shawrma",
    category: "Shawrma",
    prices: {
      Small: "190 AFN",
      Medium: "230 AFN",
      Large: "280 AFN",
      Family: "380 AFN",
    },
    description: "Chicken, melted cheese, garlic sauce, fries, and fresh pickles.",
    image: "https://images.unsplash.com/photo-1662116765994-1e4200c43589?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 26,
    name: "Family Shawrma",
    category: "Shawrma",
    prices: {
      Small: "250 AFN",
      Medium: "320 AFN",
      Large: "420 AFN",
      Family: "620 AFN",
    },
    description: "Large shawrma wrap with extra chicken, fries, garlic sauce, and cheese.",
    image: "https://images.unsplash.com/photo-1617692855027-33b14f061079?auto=format&fit=crop&w=900&q=80",
  },
];
